# Site settings
title: "ZK Blog"
brief-intro: "This is ZK Wang's personal blog."
description_footer: "ZKBlog."
url: "https://zkwang.gitee.io"
baseurl: ""
# Foot
github_username: wangzk
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
category_dir: category/
tag_dir: tag/
# excerpt
excerpt_separator: "\n\n\n\n"
gems: [jekyll-paginate]
paginate: 6
paginate_path: /page:num/
# comments
disqus_shortname: wzkblog
